### ISSUE TITLE
squatter segfaulting

### ISSUE THREAD

**Issue by Stephan76** [cyrusimap/cyrus-imapd#1811]
Hi,
with cyrus imapd 2.5.10 I started seeing crashes of squatter a couple of nights ago. The issue is 100% reprodicable and always occurs while working on the same mailbox. I ran reconstruct -G -r over the mailbox which made some corrections but the issue with squatter persists. I ran gdb:

```
Reading symbols from /usr/local/cyrus-imapd-2.5.10/bin/squatter...done.
(gdb) set args -s user.username
(gdb) run
Starting program: /usr/local/cyrus-imapd-2.5.10/bin/squatter -s user.username
[tcsetpgrp failed in terminal_inferior: Unpassender IOCTL (I/O-Control) für das Gerät]
[tcsetpgrp failed in terminal_inferior: Unpassender IOCTL (I/O-Control) für das Gerät]
[tcsetpgrp failed in terminal_inferior: Unpassender IOCTL (I/O-Control) für das Gerät]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[tcsetpgrp failed in terminal_inferior: Unpassender IOCTL (I/O-Control) für das Gerät]

Program received signal SIGSEGV, Segmentation fault.
0x0000000000404c5b in add_word_to_trie (index=0x60dd30, 
    word_ptr=0x7fff88c9ac76 "3~=3~>3~A3~B3~D3~F3~G3~I3~J3~O3~R3~X3~Z3~_3~|3~\303\063\177\002\063\177\a3\177\035\063\177\036\063\177 3\177%3\177'3\177-3\177.3\177\061\063\177\066\063\177\071\063\177A3\177B3\177J3\177L3\177W3\177Y3\177\177\063\177\303\063ÿ4\001\002\064\001\023\064\001\024\064\001\032\064\001$4\001D4\001F4\001I4\001M4\001Q4\001T4\001U4\001V4\001]4\001\303\064\002\002\064\002\004\064\002\006\064\002\017\064\002\037\064\002#4\002(4\002+4\002@4\002J4\002K4\002L4\002R4\002T4\002"..., doc_ID=48943) at imap/squat_build.c:790
790     imap/squat_build.c: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  0x0000000000404c5b in add_word_to_trie (index=0x60dd30, 
#    word_ptr=0x7fff88c9ac76 "3~=3~>3~A3~B3~D3~F3~G3~I3~J3~O3~R3~X3~Z3~_3~|3~\303\063\177\002\063\177\a3\177\035\063\177\036\063\177 3\177%3\177'3\177-3\177.3\177\061\063\177\066\063\177\071\063\177A3\177B3\177J3\177L3\177W3\177Y3\177\177\063\177\303\063ÿ4\001\002\064\001\023\064\001\024\064\001\032\064\001$4\001D4\001F4\001I4\001M4\001Q4\001T4\001U4\001V4\001]4\001\303\064\002\002\064\002\004\064\002\006\064\002\017\064\002\037\064\002#4\002(4\002+4\002@4\002J4\002K4\002L4\002R4\002T4\002"..., doc_ID=48943) at imap/squat_build.c:790
#    #1  0x00000000004061d1 in dump_index_trie_words (index=0x60dd30, first_char=191, result_offset=0x7fffffffce8c) at imap/squat_build.c:1449
#    #2  0x0000000000406666 in index_close_internal (index=0x60dd30, OK=1) at imap/squat_build.c:1589
#    #3  0x0000000000406abc in squat_index_finish (index=0x60dd30) at imap/squat_build.c:1695
#    #4  0x00000000004031ab in squat_single (state=0x60be80, incremental=0) at imap/squatter.c:480
#    #5  0x00000000004037ba in index_me (name=0x7fffffffdae0 "user.username", matchlen=0, maycreate=0, rock=0x7fffffffeae4) at imap/squatter.c:634
#    #6  0x0000000000403b88 in main (argc=3, argv=0x7fffffffebe8) at imap/squatter.c:739
```

Regards,
Stephan

**Comment by elliefm** [comment]
I've just edited the original post to format the gdb output as "code", so that github doesn't try to parse it as markdown.

**Comment by Stephan76** [comment]
Is there any hope to resolve this ? It still occurs in 2.5.11.

**Comment by rjbs** [comment]
:robot: I'm closing this issue by automation.

This issue refers only to a long-out-of-support version of Cyrus.  We're trying to get a good handle on our open issues and pull requests, so that we can reliably use them as a backlog of things we hope to work on.  If you are confident that this issue should be reconsidered, reopen it and explain why.

Remember, though, that there are only so many developers working on Cyrus, and we'd like to focus on the most important and/or low-hanging work.

Before you reopen this issue, please check that this issue is still present in the latest release of Cyrus, or the main development branch. An issue is considerably more likely to get resolved if you can provide a pull request which reproduces the issue in a Cassandane test.
