### ISSUE TITLE
mbtool segfaults

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#1817]
I Installed cyrus-imapd-3.0.0-rc2. mbtool segfaults when I use it on my account:

```
gdb --args mbtool -t user/a0620
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /usr/sbin/mbtool...done.
(gdb) run
Starting program: /usr/sbin/mbtool -t user/a0620
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Working on user/a0620...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6220036 in mbname_extname (mbname=0x0, ns=0x602140 <mbtool_namespace>, userid=0x401854 "cyrus")
    at imap/mboxname.c:981
981	    if (mbname->extname && ns == mbname->extns && !strcmpsafe(userid, mbname->extuserid))
(gdb) bt
#0  0x00007ffff6220036 in mbname_extname (mbname=0x0, ns=0x602140 <mbtool_namespace>, userid=0x401854 "cyrus")
    at imap/mboxname.c:981
#1  0x00000000004014fe in do_timestamp (mbname=0x0) at imap/mbtool.c:180
#2  0x00000000004016d9 in do_cmd (data=0x7fffffffd3e0, rock=0x7fffffffe414) at imap/mbtool.c:223
#3  0x00007ffff6217a8f in find_cb (rockp=0x7fffffffe2e0, key=0x604de0 "user.a0620.A+B[/]|$)", keylen=14,
    data=0x7ffff7fc8236 "%(A %(a0620 lrswipkxtecda1 cyrus lrswipcda anonymous 0) I 0046927d53395834 P imap2 V 1396267060 F 1 M 1485189915)", datalen=113) at imap/mboxlist.c:2395
#4  0x00007ffff5f116da in myforeach (db=0x604e10, prefix=0x7fffffffda20 "user.a0620", prefixlen=0,
    goodp=0x7ffff621758b <find_p>, cb=0x7ffff6217846 <find_cb>, rock=0x7fffffffe2e0, tidptr=0x0)
    at lib/cyrusdb_twoskip.c:1582
#5  0x00007ffff5f0338c in cyrusdb_foreach (db=0x604500, prefix=0x7fffffffda20 "user.a0620", prefixlen=0,
    p=0x7ffff621758b <find_p>, cb=0x7ffff6217846 <find_cb>, rock=0x7fffffffe2e0, tid=0x0) at lib/cyrusdb.c:241
#6  0x00007ffff6218707 in mboxlist_find_category (rock=0x7fffffffe2e0, prefix=0x7fffffffda20 "user.a0620", len=0)
    at imap/mboxlist.c:2670
#7  0x00007ffff6218f23 in mboxlist_do_find (rock=0x7fffffffe2e0, patterns=0x7fffffffe3c0) at imap/mboxlist.c:2841
#8  0x00007ffff6219196 in mboxlist_findallmulti (namespace=0x602140 <mbtool_namespace>, patterns=0x7fffffffe3c0,
    isadmin=1, userid=0x0, auth_state=0x0, proc=0x401698 <do_cmd>, rock=0x7fffffffe414) at imap/mboxlist.c:2906
#9  0x00007ffff621920d in mboxlist_findall (namespace=0x602140 <mbtool_namespace>,
    pattern=0x7fffffffe79a "user/a0620", isadmin=1, userid=0x0, auth_state=0x0, proc=0x401698 <do_cmd>,
    rock=0x7fffffffe414) at imap/mboxlist.c:2919
#10 0x000000000040146a in main (argc=3, argv=0x7fffffffe518) at imap/mbtool.c:151
```

**Comment by elliefm** [comment]
I think this will fix it, can you try it out? https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v30/1817-mbtool-segfault

**Comment by hagedose** [comment]
Thanks, that fixed it.
