### ISSUE TITLE
[2.5.x] SIG_ABRT http_dav.c

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#2117]
We tried to access cyrus-httpd via webdav from windows explorer and produced lots of coredumps with SIG_ABRT and the following bt:

#0  0x00007f5243b5d495 in raise () from /lib64/libc.so.6
#1  0x00007f5243b5ec75 in abort () from /lib64/libc.so.6
#2  0x00007f5243b9b3a7 in __libc_message () from /lib64/libc.so.6
#3  0x00007f5243ba0dee in malloc_printerr () from /lib64/libc.so.6
#4  0x00007f524801e34b in meth_propfind (txn=<value optimized out>, params=<value optimized out>)
    at imap/http_dav.c:4367
#5  0x00007f52480312ed in cmdloop () at imap/httpd.c:1378
#6  0x00007f5248031c72 in service_main (argc=<value optimized out>, argv=<value optimized out>, 
    envp=<value optimized out>) at imap/httpd.c:641
#7  0x00007f524803879a in main (argc=<value optimized out>, argv=<value optimized out>, 
    envp=0x7fff86df15a0) at master/service.c:643

Since the referenced
xmlFree(freeme->name);
is still in master I don't know if it was fixed elsewhere or if the problem still exists.

**Comment by MASHtm** [comment]
same as #2178. already fixed in 2.5.11
