### ISSUE TITLE
Email/queryChanges segfault

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2269]
I had a mailbox with 5 messages and delivered 3 new ones. Asking the client to update sent a Email/queryChanges request which ended up causing httpd to segfault.

2018-02-28T05:28:28.025308-05:00 imap21 sloti21d2t40/master[4171122]: process type:SERVICE name:httpd path:/usr/cyrus-future/libexec/httpd age:0.032s pid:1177096 signaled to death by signal 11 (Segmentation fault, core dumped)

The query looked like this:

```
0 | Email/queryChanges
1 | {…}
  accountId | ...@fastmail.fm
  collapseThreads | true
  filter | {…}
    inMailbox | 42833d8f-b9fc-46f4-a9da-d7b7b9176814
  maxChanges | 250
  sinceState | 158
  sort | {…}
    0 | {…}
      isAscending | false
      property | receivedAt
  uptoId | null
2 | 0
```

gdb backtrace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000000000048c105 in jmap_mboxlist (req=0x0, proc=0x4b7e22 <findmbox_cb>, rock=0x7ffefd735f90) at imap/http_jmap.c:276
276	    return mymblist(req->userid, req->accountid, req->authstate,
(gdb) bt
#0  0x000000000048c105 in jmap_mboxlist (req=0x0, proc=0x4b7e22 <findmbox_cb>, rock=0x7ffefd735f90) at imap/http_jmap.c:276
#1  0x00000000004b7ef7 in jmapmbox_find_uniqueid (req=0x0, id=0xa15430 "42833d8f-b9fc-46f4-a9da-d7b7b9176814") at imap/jmap_mail.c:708
#2  0x00000000004c3fb0 in parse_msgfilter_cb (filter=0xa152f0, parser=0x7ffefd7361d0, unsupported=0xa175b0, rock=0x0) at imap/jmap_mail.c:4607
#3  0x00000000004b6a8c in parse_filter (filter=0xa152f0, parser=0x7ffefd7361d0, parse_condition=0x4c3ef2 <parse_msgfilter_cb>, unsupported=0xa175b0, 
    rock=0x0) at imap/jmap_mail.c:296
#4  0x00000000004b7425 in jmap_querychanges_parse (jargs=0xa13680, parser=0x7ffefd7361d0, filter_cb=0x4c3ef2 <parse_msgfilter_cb>, filter_rock=0x0, 
    comp_cb=0x4c5e94 <parse_msgsort_cb>, sort_rock=0x0, query=0x7ffefd736210, err=0x7ffefd736198) at imap/jmap_mail.c:498
#5  0x00000000004c64b6 in getEmailsListUpdates (req=0x7ffefd736460) at imap/jmap_mail.c:5344
#6  0x000000000048db91 in jmap_post (txn=0x7ffefd7365b0, params=0x0) at imap/http_jmap.c:800
#7  0x0000000000477236 in http1_input (txn=0x7ffefd7365b0) at imap/httpd.c:1587
#8  0x0000000000477801 in cmdloop (conn=0x7ffefd7397b0) at imap/httpd.c:1734
#9  0x0000000000474ccb in service_main (argc=1, argv=0x9da040, envp=0x7ffefd73b318) at imap/httpd.c:819
#10 0x000000000048b9d5 in main (argc=3, argv=0x7ffefd73b2f8, envp=0x7ffefd73b318) at master/service.c:634
```

**Comment by rsto** [comment]
Pushed https://github.com/cyrusimap/cyrus-imapd/commit/68a0a97dfaa58152a244c19e88555492354516e8 to master. Ready for retest.

**Comment by rsto** [comment]
Closing this one. Please reopen if the issue persists.
