### ISSUE TITLE
Mailbox/set create without a name segfaults

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2354]
If you call Mailbox/set create and don't hand in a 'name' parameter for the new mailbox, httpd crashes with a segfault
````
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00000000004b999a in _mbox_newname (name=0x0, parentname=0x16a4970 "user.jt-3750a568-5463-11e8-8e94-4e915b5b6919") at imap/jmap_mail.c:1960
#2  0x00000000004ba965 in _mbox_create (req=0x7ffc5256a8b0, args=0x7ffc5256a650, mboxid=0x7ffc5256a5b0, err=0x7ffc5256a5a8) at imap/jmap_mail.c:2280
(gdb) up
#1  0x00000000004b999a in _mbox_newname (name=0x0, parentname=0x16a4970 "user.jt-3750a568-5463-11e8-8e94-4e915b5b6919") at imap/jmap_mail.c:1960
1960	    char *s = charset_to_imaputf7(name, strlen(name), cs, ENCODING_NONE);
````

**Comment by rsto** [comment]
Thanks
