### ISSUE TITLE
cyrdump crashes with floating point exception, during upgrade from 2.5.10 to 3.0.7

### ISSUE THREAD

**Issue by postilion** [cyrusimap/cyrus-imapd#2466]
Running cyrdump(8) on 3.0 (from recent HEAD) dumps core with a Floating Point Exception, as described in the original messages [in this thread](https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2018-July/004320.html).  I've just recreated this entire process from scratch.

We are upgrading an existing 2.5.10 installation, which itself was upgraded 2.4.something, back in February 2016, and from, 2.3.something prior to that.  Full reconstructs (with -V max) were performed on the mail store during the 2016 upgrade, and it has worked well since then.

In this most recent test run (both systems are KVM guests on Ubuntu Xential) we first cloned the entire system, and then ran "reconstruct -G -V max".  We then upgraded the Cyrus installation from 2.5.10 to 3.0.7 (with recent patches).  Updated the configuration files (new unixhierarchy setting) and then ran "reconstruct -V max user/onlight" to test.  That ran as expected, with none of the "uid XXX rediscovered - appending" messages we were previously getting (without having done reconstruct on the old version first, as described on mailint list).  However, while cyrdump gives us the top of the report as we would expect, it then dies:

```

    root@newmail:~# su cyrus -c "/usr/lib/cyrus/bin/cyrdump user/onlight"
    Content-Type: multipart/related; boundary="dump-7143-1533137477-281332452"

    --dump-7143-1533137477-281332452
    Content-Type: text/xml
    IMAP-Dump-Version: 0

    <imapdump uniqueid="710a47ca47ebc676">
      <mailbox-url>imap://newmail.ahwi.us/user.onlight</mailbox-url>
      <incremental-uid>0</incremental-uid>
      <nextuid>10</nextuid>

      <uidlist>1 2 3 4 5 6 7 9 </uidlist>

      <flags>
    Floating point exception (core dumped)
```

Here's a backtrace:

```
    Core was generated by `/usr/lib/cyrus/bin/cyrdump user/onlight'.
    Program terminated with signal SIGFPE, Arithmetic exception.
    #0  0x00007f83f171f955 in hash_lookup (key=key@entry=0x7ffdc18c11c0 "systemflags", 
        table=table@entry=0x7f83f1f5ce30 <attrs_by_name>) at lib/hash.c:159
    159     lib/hash.c: No such file or directory.
    (gdb) bt
    #0  0x00007f83f171f955 in hash_lookup (key=key@entry=0x7ffdc18c11c0 "systemflags", 
        table=table@entry=0x7f83f1f5ce30 <attrs_by_name>) at lib/hash.c:159
    #1  0x00007f83f1cfe822 in search_attr_find (name=<optimized out>) at imap/search_expr.c:2465
    #2  0x000055bcd5df2694 in systemflag_match (flag=1) at imap/cyrdump.c:149
    #3  0x000055bcd5df29dd in dump_me (data=<optimized out>, rock=0x7ffdc18c3490) at imap/cyrdump.c:209
    #4  0x00007f83f1cde4c3 in find_cb (rockp=rockp@entry=0x7ffdc18c33d0, 
        key=key@entry=0x7f83f2169b54 <error: Cannot access memory at address 0x7f83f2169b54>, keylen=keylen@entry=12, 
        data=data@entry=0x7f83f2169b64 <error: Cannot access memory at address 0x7f83f2169b64>, datalen=<optimized out>)
        at imap/mboxlist.c:2410
    #5  0x00007f83f19e7553 in myforeach (db=0x55bcd76e5610, prefix=0x7ffdc18c2b60 "user.onlight", prefixlen=0, 
        goodp=0x7f83f1cde2c0 <find_p>, cb=0x7f83f1cde390 <find_cb>, rock=0x7ffdc18c33d0, tidptr=<optimized out>)
        at lib/cyrusdb_skiplist.c:1177
    #6  0x00007f83f1cdc1cd in mboxlist_find_category (rock=rock@entry=0x7ffdc18c33d0, 
        prefix=prefix@entry=0x7ffdc18c2b60 "user.onlight", len=len@entry=0) at imap/mboxlist.c:2685
    #7  0x00007f83f1cdcb2c in mboxlist_do_find (rock=rock@entry=0x7ffdc18c33d0, patterns=patterns@entry=0x55bcd76e56f0)
        at imap/mboxlist.c:2877
    #8  0x00007f83f1ce1fe6 in mboxlist_findallmulti (namespace=<optimized out>, patterns=0x55bcd76e56f0, isadmin=<optimized out>, 
        userid=0x0, auth_state=<optimized out>, proc=<optimized out>, rock=0x7ffdc18c3490) at imap/mboxlist.c:2942
    #9  0x000055bcd5df24bd in main (argc=2, argv=<optimized out>) at imap/cyrdump.c:119
```

Any thoughts?
-nic

**Comment by postilion** [comment]
Further to this, we're also experiencing crashes (segmentation fault) in mbexamine(8) on the same mailbox.  Here's a test run:
```
root@newmail:~# su cyrus -c "/usr/lib/cyrus/bin/mbexamine user/onlight"
Examining user/onlight... Mailbox Header Info:
  Path to mailbox: /var/spool/cyrus/mail/I/user/onlight
  Mailbox ACL: onlight  lrswipkxtecda
  Unique ID: 710a47ca47ebc676
  User Flags: NonJunk 

 Index Header Info:
  Generation Number: 18
  Minor Version: 13
  Header Size: 128 bytes  Record Size: 104 bytes
  Number of Messages: 8  Mailbox Size: 10715 bytes  Annotations Size: 0 bytes
  Last Append Date: (1496347370) Thu Jun  1 15:02:50 2017
  UIDValidity: 1206634102  Last UID: 9
  Deleted: 0  Answered: 1  Flagged: 0
  Mailbox Options: POP3_NEW_UIDL
  Last POP3 Login: (0) Wed Dec 31 18:00:00 1969
  Highest Mod Sequence: 12

 Message Info:
000001> UID:00000001   INT_DATE:1206638350 SENTDATE:1206637200 SIZE:2924  
      > HDRSIZE:679    LASTUPD :1533135531 SYSFLAGS:00000010   LINES:64    
      > CACHEVER:3  GUID:68a5eda50d98fefd8a7c97e1a7de6a43add3d50c MODSEQ:12  THRID: 0
      > SYSTEMFLAGS: FLAG_SEEN
      > USERFLAGS: 00000000 00000000 00000000 00000001
[...]

 From>{31}<netcad.administrative@ahwi.us>
 To>{32}<onlight.administrative@ahwi.us>
 Cc>{0}
 Bcc>{0}
 Subjct>{16}"I'm in Tahiti!"
Segmentation fault (core dumped)
```
And here's the backtrace on that:
```
Core was generated by `/usr/lib/cyrus/bin/mbexamine user/onlight'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  mbname_extname (mbname=0x0, ns=0x55a44b4570a0 <mbexamine_namespace>, userid=0x55a44b255195 "cyrus") at imap/mboxname.c:983
983     imap/mboxname.c: No such file or directory.
(gdb) bt
#0  mbname_extname (mbname=0x0, ns=0x55a44b4570a0 <mbexamine_namespace>, userid=0x55a44b255195 "cyrus") at imap/mboxname.c:983
#1  0x000055a44b254530 in do_examine (data=0x7ffc2274fcf0, rock=<optimized out>) at imap/mbexamine.c:208
#2  0x00007f47197684c3 in find_cb (rockp=rockp@entry=0x7ffc22750b30, 
    key=key@entry=0x7f4719be3fe4 <error: Cannot access memory at address 0x7f4719be3fe4>, keylen=keylen@entry=19, 
    data=data@entry=0x7f4719be3ffc <error: Cannot access memory at address 0x7f4719be3ffc>, datalen=<optimized out>)
    at imap/mboxlist.c:2410
#3  0x00007f4719471553 in myforeach (db=0x55a44bae1610, prefix=0x7ffc227502c0 "user.onlight", prefixlen=0, 
    goodp=0x7f47197682c0 <find_p>, cb=0x7f4719768390 <find_cb>, rock=0x7ffc22750b30, tidptr=<optimized out>)
    at lib/cyrusdb_skiplist.c:1177
#4  0x00007f47197661cd in mboxlist_find_category (rock=rock@entry=0x7ffc22750b30, 
    prefix=prefix@entry=0x7ffc227502c0 "user.onlight", len=len@entry=0) at imap/mboxlist.c:2685
#5  0x00007f4719766b2c in mboxlist_do_find (rock=rock@entry=0x7ffc22750b30, patterns=patterns@entry=0x7ffc22750c00)
    at imap/mboxlist.c:2877
#6  0x00007f471976bfe6 in mboxlist_findallmulti (namespace=<optimized out>, namespace@entry=0x55a44b4570a0 <mbexamine_namespace>, 
    patterns=patterns@entry=0x7ffc22750c00, isadmin=isadmin@entry=1, userid=userid@entry=0x0, auth_state=auth_state@entry=0x0, 
    proc=proc@entry=0x55a44b2544e0 <do_examine>, rock=0x0) at imap/mboxlist.c:2942
#7  0x00007f471976c0ba in mboxlist_findall (namespace=0x55a44b4570a0 <mbexamine_namespace>, pattern=<optimized out>, isadmin=1, 
    userid=0x0, auth_state=0x0, proc=0x55a44b2544e0 <do_examine>, rock=0x0) at imap/mboxlist.c:2955
#8  0x000055a44b2539ff in main (argc=2, argv=<optimized out>) at imap/mbexamine.c:169
(gdb) quit
```
Cheers,
-nic

**Comment by elliefm** [comment]
I get this funny feeling like I've seen floating point exceptions from cyrdump before but I can't for the life of me remember the context

Any chance you can reproduce the backtraces with a non-optimised build?

**Comment by karagian** [comment]
About mbexamine error, it seems unrelated to the whole upgrade process. I can see it happening on newly created mailboxes on cyrus 3.0.x. Furthermore, the trigger to the error seems to be the fact that the target mailbox has other mailboxes under it... The problem does not occur when target mailbox is a leaf mailbox

**Comment by postilion** [comment]
@elliefm Here is a cyrdump back trace from -O0 built code:
```
Core was generated by `/usr/lib/cyrus/bin/cyrdump user/onlight'.
Program terminated with signal SIGFPE, Arithmetic exception.
#0  0x00007fb7fda5cf8f in hash_lookup (key=0x7ffc1b803ae0 "systemflags", table=0x7fb7fe2e81e0 <attrs_by_name>) at lib/hash.c:156
156	lib/hash.c: No such file or directory.
(gdb) bt
#0  0x00007fb7fda5cf8f in hash_lookup (key=0x7ffc1b803ae0 "systemflags", table=0x7fb7fe2e81e0 <attrs_by_name>) at lib/hash.c:156
#1  0x00007fb7fe07b6ee in search_attr_find (name=0x563d0693a25e "systemflags") at imap/search_expr.c:2465
#2  0x0000563d069397fe in systemflag_match (flag=1) at imap/cyrdump.c:149
#3  0x0000563d06939b00 in dump_me (data=0x7ffc1b804f00, rock=0x7ffc1b805ea0) at imap/cyrdump.c:209
#4  0x00007fb7fe05360d in find_cb (rockp=0x7ffc1b805df0, 
    key=0x7fb7fe4f4b54 <error: Cannot access memory at address 0x7fb7fe4f4b54>, keylen=12, 
    data=0x7fb7fe4f4b64 <error: Cannot access memory at address 0x7fb7fe4f4b64>, datalen=71) at imap/mboxlist.c:2410
#5  0x00007fb7fdd29d00 in myforeach (db=0x563d086a8610, prefix=0x7ffc1b805570 "user.onlight", prefixlen=0, 
    goodp=0x7fb7fe053044 <find_p>, cb=0x7fb7fe0533b8 <find_cb>, rock=0x7ffc1b805df0, tidptr=0x0) at lib/cyrusdb_skiplist.c:1177
#6  0x00007fb7fdd21e14 in cyrusdb_foreach (db=0x563d086a85f0, prefix=0x7ffc1b805570 "user.onlight", prefixlen=0, 
    p=0x7fb7fe053044 <find_p>, cb=0x7fb7fe0533b8 <find_cb>, rock=0x7ffc1b805df0, tid=0x0) at lib/cyrusdb.c:241
#7  0x00007fb7fe0543dc in mboxlist_find_category (rock=0x7ffc1b805df0, prefix=0x7ffc1b805570 "user.onlight", len=0)
    at imap/mboxlist.c:2685
#8  0x00007fb7fe054ef0 in mboxlist_do_find (rock=0x7ffc1b805df0, patterns=0x563d086a86f0) at imap/mboxlist.c:2877
#9  0x00007fb7fe0551ee in mboxlist_findallmulti (namespace=0x7fb7fe2de8e0 <ns>, patterns=0x563d086a86f0, isadmin=1, userid=0x0, 
    auth_state=0x0, proc=0x563d0693981d <dump_me>, rock=0x7ffc1b805ea0) at imap/mboxlist.c:2942
#10 0x0000563d069396e7 in main (argc=2, argv=0x7ffc1b805fb8) at imap/cyrdump.c:119
```

And here's the same from mbexamine:
```
Core was generated by `/usr/lib/cyrus/bin/mbexamine user/onlight'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f134e775b4b in mbname_extname (mbname=0x0, ns=0x55acbfed6080 <mbexamine_namespace>, userid=0x55acbfcd456b "cyrus")
    at imap/mboxname.c:983
983	imap/mboxname.c: No such file or directory.
(gdb) bt
#0  0x00007f134e775b4b in mbname_extname (mbname=0x0, ns=0x55acbfed6080 <mbexamine_namespace>, userid=0x55acbfcd456b "cyrus")
    at imap/mboxname.c:983
#1  0x000055acbfcd2d45 in do_examine (data=0x7ffee6f19d40, rock=0x0) at imap/mbexamine.c:208
#2  0x00007f134e76c60d in find_cb (rockp=0x7ffee6f1ac30, 
    key=0x7f134ec0dbd8 <error: Cannot access memory at address 0x7f134ec0dbd8>, keylen=19, 
    data=0x7f134ec0dbf0 <error: Cannot access memory at address 0x7f134ec0dbf0>, datalen=71) at imap/mboxlist.c:2410
#3  0x00007f134e442d00 in myforeach (db=0x55acc1d9d610, prefix=0x7ffee6f1a3b0 "user.onlight", prefixlen=0, 
    goodp=0x7f134e76c044 <find_p>, cb=0x7f134e76c3b8 <find_cb>, rock=0x7ffee6f1ac30, tidptr=0x0) at lib/cyrusdb_skiplist.c:1177
#4  0x00007f134e43ae14 in cyrusdb_foreach (db=0x55acc1d9d5f0, prefix=0x7ffee6f1a3b0 "user.onlight", prefixlen=0, 
    p=0x7f134e76c044 <find_p>, cb=0x7f134e76c3b8 <find_cb>, rock=0x7ffee6f1ac30, tid=0x0) at lib/cyrusdb.c:241
#5  0x00007f134e76d3dc in mboxlist_find_category (rock=0x7ffee6f1ac30, prefix=0x7ffee6f1a3b0 "user.onlight", len=0)
    at imap/mboxlist.c:2685
#6  0x00007f134e76def0 in mboxlist_do_find (rock=0x7ffee6f1ac30, patterns=0x7ffee6f1ad20) at imap/mboxlist.c:2877
#7  0x00007f134e76e1ee in mboxlist_findallmulti (namespace=0x55acbfed6080 <mbexamine_namespace>, patterns=0x7ffee6f1ad20, 
    isadmin=1, userid=0x0, auth_state=0x0, proc=0x55acbfcd2cdc <do_examine>, rock=0x0) at imap/mboxlist.c:2942
#8  0x00007f134e76e29b in mboxlist_findall (namespace=0x55acbfed6080 <mbexamine_namespace>, pattern=0x7ffee6f1c883 "user/onlight", 
    isadmin=1, userid=0x0, auth_state=0x0, proc=0x55acbfcd2cdc <do_examine>, rock=0x0) at imap/mboxlist.c:2955
#9  0x000055acbfcd2c38 in main (argc=2, argv=0x7ffee6f1be88) at imap/mbexamine.c:169
```

I hope it's helpful.
-nic

**Comment by elliefm** [comment]
Well, I've got a fix for the cyrdump SIGFPE, but now it SIGSEGVs at a later point...

**Comment by elliefm** [comment]
Okay, these two cyrdump commits seem to do the trick for me (but my test data is utterly trivial, so there might be more gremlins hiding in here):

2397a8f24 -- fixes SIGFPE due to search state not being properly initialised
79c9432e0 -- fixes SIGSEGV due to an array overrun

They're both on the cyrus-imapd-3.0 branch, and I'm about to cherry-pick them to master too, because it looks like it probably has the same issues.

Looks like 2.5 wasn't affected by this because it had a slightly different way of going about dumping.

**Comment by elliefm** [comment]
And I think this should fix mbexamine: 217ac39ef (also now on cyrus-imapd-3.0 branch, and about to be cherry-picked to master)

**Comment by postilion** [comment]
@elliefm Great!  I'll try building and testing these later today.  Thanks! :-)
-nic

**Comment by postilion** [comment]
@elliefm Thanks again, so much.  Both of these fixes work just fine.  I'm going to proceed with my upgrade now. :-)

Yours,
-nic
