### ISSUE TITLE
ipurge segfaults on cyrus 3.0.x

### ISSUE THREAD

**Issue by javier-angulo** [cyrusimap/cyrus-imapd#2524]
Hello all,
we run nightly ipurge on all users Trash folders
`ipurge -C /srv/llcb554-a/etc/imapd.conf -s -X -f -d 31 user/*/Trash`
but after a few succesful run on some users,ipurge always segfaults
`master[4101]: process type:EVENT name:purgeTrash path:/usr/sbin/ipurge age:0.031s pid:5995 signaled to death by signal 11 (Segmentation fault)`

We are (succesfully) running cyrus 3.0.5 on production; upgrading to 3.0.8 does not help either.
Here is a backtrace from gdb on cyrus 3.0.8:
```
(gdb) run -C /srv/llcbxxx-a/etc/imapd.conf -v -s -X -f -d 31 user/xxx594c/Trash
Starting program: /usr/sbin/ipurge -C /srv/llcbxxx-a/etc/imapd.conf -v -s -X -f -d 31 user/xxx594c/Trash
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Working on user.xxx594c.Trash...
Total messages    		 0
Total bytes       		 0
Deleted messages  		 0
Deleted bytes     		 0
Remaining messages		 0
Remaining bytes   		 0

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff623298f in mbname_intname (mbname=0x0) at imap/mboxname.c:789
789	{
Missing separate debuginfos, use: debuginfo-install cyrus-sasl-lib-2.1.26-23.el7.x86_64 glibc-2.17-222.el7.x86_64 jansson-2.10-1.el7.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-19.el7.x86_64 libcom_err-1.42.9-12.el7_5.x86_64 libgcc-4.8.5-28.el7_5.1.x86_64 libicu-50.1.2-15.el7.x86_64 libselinux-2.5-12.el7.x86_64 libstdc++-4.8.5-28.el7_5.1.x86_64 libuuid-2.23.2-52.el7_5.1.x86_64 nss-softokn-freebl-3.36.0-5.el7_5.x86_64 openssl-libs-1.0.2k-12.el7.x86_64 pcre-8.32-17.el7.x86_64 sqlite-3.7.17-8.el7.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff623298f in mbname_intname (mbname=0x0) at imap/mboxname.c:789
#1  0x0000000000401846 in purge_me (data=0x7fffffffd540, rock=<optimized out>)
    at imap/ipurge.c:240
#2  0x00007ffff6229c3b in find_cb (rockp=rockp@entry=0x7fffffffe3a0, key=<optimized out>, 
    keylen=<optimized out>, 
    data=data@entry=0x7ffff7ff52b7 "%(A %(xxx594c lrswipkxtecda) P llcbxxx-a M 1536916110)", 
    datalen=datalen@entry=54) at imap/mboxlist.c:2410
#3  0x00007ffff5f3a9fe in myforeach (db=0x605ed0, 
    prefix=0x7fffffffdb30 "user.xxx594c.Trash", prefixlen=0, goodp=0x7ffff6229a40 <find_p>, 
    cb=0x7ffff6229b00 <find_cb>, rock=0x7fffffffe3a0, tidptr=<optimized out>)
    at lib/cyrusdb_twoskip.c:1580
#4  0x00007ffff6227a5b in mboxlist_find_category (rock=rock@entry=0x7fffffffe3a0, 
    prefix=prefix@entry=0x7fffffffdb30 "user.xxx594c.Trash", len=len@entry=0)
    at imap/mboxlist.c:2685
#5  0x00007ffff6228329 in mboxlist_do_find (rock=rock@entry=0x7fffffffe3a0, 
    patterns=patterns@entry=0x606a50) at imap/mboxlist.c:2877
#6  0x00007ffff622d7e6 in mboxlist_findallmulti (namespace=<optimized out>, 
    namespace@entry=0x0, patterns=patterns@entry=0x606a50, isadmin=isadmin@entry=1, 
    userid=userid@entry=0x0, auth_state=auth_state@entry=0x0, 
    proc=proc@entry=0x401810 <purge_me>, rock=rock@entry=0x0) at imap/mboxlist.c:2942
#7  0x000000000040160a in main (argc=10, argv=0x7fffffffe568) at imap/ipurge.c:200
(gdb) 
```
Thanks for your time and help,
Javier.

**Comment by elliefm** [comment]
This is now fixed in git, and will be included in the next release. :)

In the meantime, you could manually apply this patch: 4c8c9923c6589f0ea0fd4267f84524e43b2ea9a8
