### ISSUE TITLE
squatter: fatal error: Internal error: assertion failed

### ISSUE THREAD

**Issue by KimBrodowski** [cyrusimap/cyrus-imapd#2742]
Hello, 
this issue is an excerpt from https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927142 where I discussed a couple of issues we're facing when upgrading to Cyrus 3.

Without having verified this yet (I haven't found the time to compile Cyrus from source and actually verify that the issues still exists here) I believe the following issue is an "upstream" issue and should be fixed here. When calling squatter sometimes - depending on how you specify the mailbox to generate squat files for - squatter will crash.

Debian Buster(Cyrus 3.0.8-4):
```
busternt.kim.mein-iserv.de ~ # /usr/sbin/cyrus squatter -u kim.brodowski
cyrus/squatter[17830]: indexing mailboxes
cyrus/squatter[17830]: indexing mailbox user/kim.brodowski...
cyrus/squatter[17830]: indexing mailbox user/kim.brodowski/Drafts...
cyrus/squatter[17830]: indexing mailbox user/kim.brodowski/Junk...
cyrus/squatter[17830]: indexing mailbox user/kim.brodowski/Sent...
cyrus/squatter[17830]: indexing mailbox user/kim.brodowski/Trash...
cyrus/squatter[17830]: done indexing mailboxes
busternt.kim.mein-iserv.de ~ # /usr/sbin/cyrus squatter 
user/kim.brodowski/Sent
cyrus/squatter[19346]: indexing mailboxes
cyrus/squatter[19346]: indexing mailbox user/kim.brodowski/Sent...
cyrus/squatter[19346]: done indexing mailboxes
busternt.kim.mein-iserv.de ~ # /usr/sbin/cyrus squatter user/kim^brodowski
fatal error: Internal error: assertion failed: lib/cyrusdb_twoskip.c: 
2339: keylen
```

Compared to Stretch (Cyrus 2.5.10-3):
```
stable.iserv.eu /etc # /usr/sbin/cyrus squatter user/kim.brodowski -v
Indexing mailbox user/kim.brodowski... Indexed 401 messages (7007950 
bytes) into 942379 index bytes in 0 seconds
stable.iserv.eu /etc # /usr/sbin/cyrus squatter user/kim^brodowski -v
Indexing mailbox user/kim.brodowski... Indexed 401 messages (7007950 
bytes) into 942379 index bytes in 0 seconds
```
Even if this way of specifying a mailbox is no longer supported I'd expect a clean error message.

Kind regards,
Kim-A. Brodowski

**Comment by brong** [comment]
Yeah, this is incorrectly crashing rather than just saying "invalid mailbox name"

**Comment by dilyanpalauzov** [comment]
Concering the original report at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927142:

In theory, when an old SIeve script version is detected, Cyrus automatically recompiles it to a new version.  For user names with dots, timsieved used to upload the Sieve scripts in one place, and lmtp_sieve/deliver looked for them on another place.  This was fixed in Cyrus Imap 3.0.6.  I wonder, how has this worked in 2.5 for the script `/var/spool/sieve/k/kim.brodowski/user.bc`.

For the backtrace:

```
#0  0x00007f65d13e3dd9 in __bswap_32 (__bsx=<error reading variable: Cannot access memory at address 0xc>) at /usr/include/x86_64-linux-gnu/bits/byteswap.h:52
#1  sieve_bytecode_version (bc=0x561a85a80b00) at sieve/bc_eval.c:1809

#2  0x00007f65d13ea032 in sieve_rebuild (script_fname=0x561a85a80aa0 "/var/spool/sieve/k/kim.brodowski/user.script", script_fname@entry=0x0, bc_fname=bc_fname@entry=0x7ffc656e2f50 "/var/spool/sieve/k/kim.brodowski/user.bc", force=force@entry=0, out_parse_errors=out_parse_errors@entry=0x0) at sieve/rebuild.c:203

#3  0x0000561a8413633e in sieve_find_script (user=<optimized out>, domain=domain@entry=0x0, script=script@entry=0x7f65d1403020 <error: Cannot access memory at address 0x7f65d1403020>, fname=fname@entry=0x7ffc656e2f50 "/var/spool/sieve/k/kim.brodowski/user.bc", size=size@entry=4096) at imap/lmtp_sieve.c:894

#4  0x0000561a84136e7d in getinclude (sc=0x7ffc656e50a0, script=0x7f65d1403020 <error: Cannot access memory at address 0x7f65d1403020>, isglobal=0, fname=0x7ffc656e2f50 "/var/spool/sieve/k/kim.brodowski/user.bc", size=4096) at imap/lmtp_sieve.c:241

#5  0x00007f65d13e445a in sieve_eval_bc (exe=<optimized out>, exe@entry=0x561a85a7de00, is_incl=is_incl@entry=0, i=i@entry=0x561a85a7cbf0, sc=sc@entry=0x7ffc656e50a0, m=m@entry=0x7ffc656e61f0, variables=variables@entry=0x7ffc656e4010, actions=0x561a85a56e40, notify_list=0x561a85a80a60, errmsg=0x7ffc656e3ff0) at sieve/bc_eval.c:2516

#6  0x00007f65d13ebc93 in sieve_execute_bytecode (exe=0x561a85a7de00, interp=interp@entry=0x561a85a7cbf0, script_context=script_context@entry=0x7ffc656e50a0, message_context=message_context@entry=0x7ffc656e61f0) at sieve/script.c:953
```

This is not good `getinclude (…script=0x7f65d1403020 <error: Cannot access memory at address 0x7f65d1403020>…)`. It comes from bc_eval.c:2516:
```C
ip = unwrap_string(bc, ip+1, &data, NULL);
if (requires & BFE_VARIABLES) {
    data = parse_string(data, variables);
}

res = i->getinclude(sc, data, isglobal, fpath, sizeof(fpath));
```
Any chance to get that user.script and user.bc before the scripts were rebuild for 3.0?
