### ISSUE TITLE
A certain MIME structure crashes Email/import and Email/get

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2918]
The following email crashes cyrus in Email/import or in Email/get or other code that uses the underlying _email_extract_bodies_internal:

```
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="15741819384.667F.1459"
Content-Transfer-Encoding: 7bit


--15741819384.667F.1459
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="15741819381.6ac2A9D.1459"
Content-Transfer-Encoding: 7bit


--15741819381.6ac2A9D.1459
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: text/plain

a
--15741819381.6ac2A9D.1459
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="15741819380.5ff8F6c.1459"
Content-Transfer-Encoding: 7bit


--15741819380.5ff8F6c.1459
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: text/plain

b
--15741819380.5ff8F6c.1459
Date: Tue, 19 Nov 2019 11:45:38 -0500
MIME-Version: 1.0
Content-Type: text/html

c
--15741819380.5ff8F6c.1459--

--15741819381.6ac2A9D.1459--

--15741819384.667F.1459--
```

That structure is, more simply:

```
    my $email =
      cmultipart("alternative", [
        cmultipart("mixed", [
          cpart("text/plain", "a"),
          cmultipart('alternative', [
            cpart("text/plain", "b"),
            cpart("text/html", "c"),
          ]),
        ]),
      ]);
```

The crash:
```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5cab2e4467 in ptrarray_append (pa=0x0, p=0x1f4a660) at lib/ptrarray.c:125
125	    ensure_alloc(pa, pa->count+1);
(gdb) bt
#0  0x00007f5cab2e4467 in ptrarray_append (pa=0x0, p=0x1f4a660) at lib/ptrarray.c:125
#1  0x00000000004f4c3e in _email_extract_bodies_internal (parts=0x1f4a4f0, nparts=2, multipart_type=0x1f42d20 "ALTERNATIVE", in_alternative=1, textlist=0x7ffec8774b90, htmllist=0x0, attslist=0x7ffec8774b80)
    at imap/jmap_mail_query.c:402
#2  0x00000000004f4bdd in _email_extract_bodies_internal (parts=0x1f42da0, nparts=2, multipart_type=0x1f2e900 "MIXED", in_alternative=1, textlist=0x7ffec8774b90, htmllist=0x0, attslist=0x7ffec8774b80)
    at imap/jmap_mail_query.c:390
#3  0x00000000004f4bdd in _email_extract_bodies_internal (parts=0x1f429b0, nparts=1, multipart_type=0x1f2ed50 "ALTERNATIVE", in_alternative=1, textlist=0x7ffec8774b90, htmllist=0x7ffec8774ba0, 
    attslist=0x7ffec8774b80) at imap/jmap_mail_query.c:390
#4  0x00000000004f4bdd in _email_extract_bodies_internal (parts=0x1f2f310, nparts=1, multipart_type=0x5334c0 "MIXED", in_alternative=0, textlist=0x7ffec8774b90, htmllist=0x7ffec8774ba0, 
    attslist=0x7ffec8774b80) at imap/jmap_mail_query.c:390
#5  0x00000000004f4dfc in jmap_emailbodies_extract (root=0x1f2f310, bodies=0x7ffec8774b80) at imap/jmap_mail_query.c:447
#6  0x00000000004dea5d in _email_get_bodies (req=0x7ffec8775220, args=0x7ffec8774dc0, msg=0x1f2f7d0, email=0x1f42b30) at imap/jmap_mail.c:5439
#7  0x00000000004df5dd in _email_from_msg (req=0x7ffec8775220, args=0x7ffec8774dc0, msg=0x1f2f7d0, emailptr=0x7ffec8774d18) at imap/jmap_mail.c:5627
#8  0x00000000004df91b in _email_from_buf (req=0x7ffec8775220, args=0x7ffec8774dc0, buf=0x7ffec8774d80, encoding=0x0, emailptr=0x7ffec8774d18) at imap/jmap_mail.c:5701
#9  0x00000000004f0dae in _email_import (req=0x7ffec8775220, jemail_import=0x1f33f60, new_email=0x7ffec8774ed0, err=0x7ffec8774ed8) at imap/jmap_mail.c:10751
#10 0x00000000004f1701 in jmap_email_import (req=0x7ffec8775220) at imap/jmap_mail.c:10896
#11 0x00000000004987ae in jmap_api (txn=0x7ffec8775420, res=0x7ffec8775380, settings=0x75a560 <my_jmap_settings>) at imap/jmap_api.c:828
#12 0x000000000049435d in meth_post (txn=0x7ffec8775420, params=0x0) at imap/http_jmap.c:363
#13 0x000000000047f746 in process_request (txn=0x7ffec8775420) at imap/httpd.c:1788
#14 0x000000000047f986 in http1_input (txn=0x7ffec8775420) at imap/httpd.c:1854
#15 0x000000000047ff3c in cmdloop (conn=0x7ffec8778650) at imap/httpd.c:2002
#16 0x000000000047d2f1 in service_main (argc=1, argv=0x1f19080, envp=0x7ffec8779e88) at imap/httpd.c:941
#17 0x0000000000493b85 in main (argc=3, argv=0x7ffec8779e68, envp=0x7ffec8779e88) at master/service.c:637
```

The loop of going through subparts sets htmllist to a null pointer in this case:
```
            else if (in_alternative) {
                if (parttype == PLAIN)
                    htmllist = NULL;
                if (parttype == HTML)
                    textlist = NULL;
            }
```

but later, if there's another multipart, recurses down again with that null pointer, and attempts to append to htmllist if there's an html part:

```
        if (parttype == MULTIPART) {
            _email_extract_bodies_internal(part->subpart, part->numparts,
                    part->subtype,
                    in_alternative || !strcmp(part->subtype, "ALTERNATIVE"),
                    textlist, htmllist, attslist);
```

and in that recursed loop again:

```
            if (textlist)
                ptrarray_append(textlist, (void*) part);
            if (htmllist)
                ptrarray_append(htmllist, (void*) part);
            if ((!textlist || !htmllist) && parttype == INLINE_MEDIA)
                ptrarray_append(attslist, (void*) part);
```

**Comment by wolfsage** [comment]
Oh, sorry, I copied the wrong part of the recursed loop. Should have been this (where the actual crash happens)

```
        else if (is_inline) {
            if (!strcmp(multipart_type, "ALTERNATIVE")) {
                switch (parttype) {
                    case PLAIN:
                        ptrarray_append(textlist, (void*) part);
                        break;
                    case HTML:
                        ptrarray_append(htmllist, (void*) part);
                        break;
                    default:
                        ptrarray_append(attslist, (void*) part);
                }
                continue;
            }
```
