### ISSUE TITLE
imapd crashes on list command with imapd: free(): invalid next size

### ISSUE THREAD

**Issue by buschmann23** [cyrusimap/cyrus-imapd#3125]
The following crash happens for me on 3.2.2, 3.0.13 - but not on 2.5.15.

```
2 list "" "*"
*** Error in `imapd': free(): invalid next size(fast): 0x000055f4870f9310 ***
Connection closed by foreign host.
```
Log says:
```
master[15060]: process type:SERVICE name:imap path:/usr/lib/cyrus/bin/imapd age:88.744s pid:15198 signaled to death by signal 6 (Aborted, core dumped)
```
GDB backtrace:
```
Program received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
51	}
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007fca6ee8ab01 in __GI_abort () at abort.c:79
#2  0x00007fca6eecc957 in __libc_message (action=action@entry=(do_abort | do_backtrace), fmt=fmt@entry=0x7fca6efd5b30 "*** Error in `%s': %s: 0x%s ***\n")
    at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007fca6eed3173 in malloc_printerr (action=<optimized out>, str=0x7fca6efd5f00 "free(): invalid next size (fast)", ptr=<optimized out>, 
    ar_ptr=<optimized out>) at malloc.c:5428
#4  0x00007fca6eed4a79 in _int_free (av=0x7fca6f204aa0 <main_arena>, p=<optimized out>, have_lock=<optimized out>) at malloc.c:4170
#5  0x00007fca704b5bd1 in glob_free (gp=gp@entry=0x7ffcd23daed8) at lib/glob.c:125
#6  0x00007fca707b382c in mboxlist_do_find (rock=rock@entry=0x7ffcd23dbb50, patterns=patterns@entry=0x7ffcd23dbfc8) at imap/mboxlist.c:2889
#7  0x00007fca707b97f6 in mboxlist_findallmulti (namespace=<optimized out>, namespace@entry=0x650100 <imapd_namespace>, 
    patterns=patterns@entry=0x7ffcd23dbfc8, isadmin=<optimized out>, userid=0x12c23b0 "buschmann", auth_state=<optimized out>, 
    proc=proc@entry=0x420980 <list_cb>, rock=0x7ffcd23dbc80) at imap/mboxlist.c:2920
#8  0x0000000000412021 in list_data (listargs=0x7ffcd23dbfb0) at imap/imapd.c:13116
#9  cmd_list (tag=0x12c2090 "2", listargs=listargs@entry=0x7ffcd23dbfb0) at imap/imapd.c:7824
#10 0x000000000042b363 in cmdloop () at imap/imapd.c:1657
#11 0x000000000042fbcc in service_main (argc=<optimized out>, argv=<optimized out>, envp=envp@entry=0x7ffcd23dffe8) at imap/imapd.c:1000
#12 0x0000000000413ac5 in main (argc=<optimized out>, argv=<optimized out>, envp=0x7ffcd23dffe8) at master/service.c:634
```

Build configuration for version 3.0.13 with gcc 7.5 on glibc 2.26 ([complete build configuration/log](https://paste.opensuse.org/91086480))
```
CFLAGS='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g'
CXXFLAGS='-fmessage-length=0 -grecord-gcc-switches -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g'

./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/lib --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --disable-dependency-tracking --localstatedir=/var/lib --bindir=/usr/lib/cyrus/bin --libexecdir=/usr/lib/cyrus/bin --sbindir=/usr/lib/cyrus/bin --enable-idled --enable-murder --enable-nntp --enable-replication --enable-autocreate --enable-xapian --enable-http --enable-unit-tests --enable-gssapi --with-gss_impl=mit --with-libcap --with-ldap=/usr --with-mysql --with-pgsql --with-pgsql-incdir=/usr/include/pgsql --with-lmdb --with-cyrus-user=cyrus --with-syslogfacility=DAEMON --with-lock=fcntl --with-perl=perl --with-com_err
```

After reading #3035 and #1981 I tried to build it with `-O0 -U_FORTIFY_SOURCE` but without any change on the crash.

**Comment by buschmann23** [comment]
This was a duplicate of #1731 and/or #2629 - at least using a libpcre with the proposed patch applied fixes the issue for me.
