### ISSUE TITLE
"quota -f -q" crashes when run on a murder frontend

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3613]
```
(gdb) bt
#0  __strlen_avx2 () at ../sysdeps/x86_64/multiarch/strlen-avx2.S:65
#1  0x00007f63591f91aa in xstrdup (str=0x0) at lib/xmalloc.c:88
#2  0x00007f6359343e7e in mailbox_open_advanced (name=0x563749c4a3c0 "user.cassandane", 
    locktype=1, index_locktype=2, mailboxptr=0x7fff972e80a8) at imap/mailbox.c:1081
#3  0x00007f6359344039 in mailbox_open_iwl (name=0x563749c4a3c0 "user.cassandane", 
    mailboxptr=0x7fff972e80a8) at imap/mailbox.c:1121
#4  0x00005637480124ca in fixquota_dombox (mbentry=0x563749c4ad30, rock=0x7fff972e8440)
    at imap/quota.c:471
#5  0x00007f6359365e77 in allmbox_cb (rock=0x7fff972e8380, 
    key=0x563749c4a140 "Nuser\037cassandane", keylen=16, 
    data=0x7f63591d0350 <error: Cannot access memory at address 0x7f63591d0350>, 
    datalen=108) at imap/mboxlist.c:3487
#6  0x00007f635895315b in myforeach (db=0x563749c49ca0, 
    prefix=0x563749c4aa90 "N\375\031Yc\177", prefixlen=1, 
    goodp=0x7f6359365e92 <allmbox_p>, cb=0x7f6359365d84 <allmbox_cb>, 
    rock=0x7fff972e8380, tidptr=0x0) at lib/cyrusdb_twoskip.c:1651
#7  0x00007f6358942a0b in cyrusdb_foreach (db=0x563749c49c80, 
    prefix=0x563749c4aa90 "N\375\031Yc\177", prefixlen=1, p=0x7f6359365e92 <allmbox_p>, 
    cb=0x7f6359365d84 <allmbox_cb>, rock=0x7fff972e8380, tid=0x0) at lib/cyrusdb.c:281
#8  0x00007f6359366188 in mboxlist_allmbox (prefix=0x563749c4a3e0 "", 
    proc=0x5637480123c2 <fixquota_dombox>, rock=0x7fff972e8440, flags=0)
    at imap/mboxlist.c:3544
#9  0x0000563748012c19 in fixquota_dopass (domain=0x0, roots=0x7fff972e8a00, nroots=0, 
    cb=0x5637480123c2 <fixquota_dombox>, isuser=0) at imap/quota.c:629
#10 0x0000563748012e5c in fixquotas (domain=0x0, roots=0x7fff972e8a00, nroots=0, 
    isuser=0) at imap/quota.c:667
#11 0x00005637480118de in main (argc=5, argv=0x7fff972e89d8) at imap/quota.c:202
(gdb) f 2
#2  0x00007f6359343e7e in mailbox_open_advanced (name=0x563749c4a3c0 "user.cassandane", 
    locktype=1, index_locktype=2, mailboxptr=0x7fff972e80a8) at imap/mailbox.c:1081
1081	    mailbox->uniqueid = xstrdup(mbentry->uniqueid);
(gdb) list
1076	    mailbox->part = xstrdup(mbentry->partition);
1077	
1078	    /* Note that the header does have the uniqueid and ACL information,
1079	     * but it is only backup, and the mboxlist data is considered authoritative,
1080	     * so we will just use what we were passed */
1081	    mailbox->uniqueid = xstrdup(mbentry->uniqueid);
1082	    mailbox->acl = xstrdup(mbentry->acl);
1083	    mailbox->mbtype = mbentry->mbtype;
1084	    mailbox->foldermodseq = mbentry->foldermodseq;
1085	
```

At this line of mailbox_open_advanced:

```
1081	    mailbox->uniqueid = xstrdup(mbentry->uniqueid);
```

I don't really know what frontend mailboxes.db entries look like but I guess they don't contain uniqueid's.

It would be nice if quota would detect that it's unable to do this task on a frontend and exit with an error, instead of crashing out!

**Comment by elliefm** [comment]
I think this was fixed by 4250f90ef5c in #3611
