### ISSUE TITLE
JMAP crash on Cyrus 3.2

### ISSUE THREAD

**Issue by mildred** [cyrusimap/cyrus-imapd#3766]
Hello,

Experimenting with JMAP, I could make it segfault. I did it by geeding to Email/get (create operation) an email object I got using Email/get (after I removed the properties: id, blobId, threadId, size, trustedSender, hasAttachment, preview)

The request JSON payload:

```js
{
  "using": [
    "urn:ietf:params:jmap:core",
    "https://cyrusimap.org/ns/jmap/quota",
    "https://cyrusimap.org/ns/jmap/performance",
    "https://cyrusimap.org/ns/jmap/debug",
    "https://cyrusimap.org/ns/jmap/blob",
    "urn:ietf:params:jmap:mail",
    "https://cyrusimap.org/ns/jmap/search",
    "https://cyrusimap.org/ns/jmap/mail",
    "urn:ietf:params:jmap:submission",
    "urn:ietf:params:jmap:vacationresponse",
    "https://cyrusimap.org/ns/jmap/contacts",
    "https://cyrusimap.org/ns/jmap/calendars"
  ],
  "methodCalls": [
    [
      "Email/set",
      {
        "accountId": "mildred@mildred.fr",
        "create": {
          "draft": {
            "mailboxIds": {
              "orpjtqwuv22a7tvwdk3vl8ly": true
            },
            "removedDates": {},
            "addedDates": {
              "orpjtqwuv22a7tvwdk3vl8ly": "2021-11-09T22:47:00Z"
            },
            "keywords": {},
            "receivedAt": "2021-11-09T22:47:00Z",
            "spamScore": null,
            "snoozed": null,
            "references": null,
            "sender": null,
            "replyTo": null,
            "messageId": [
              "mae22z8hw8umzhd4aiab76gh@os-gravelines-1.webmsg.me"
            ],
            "inReplyTo": null,
            "from": [
              {
                "name": null,
                "email": "mildred@mildred.fr"
              }
            ],
            "to": null,
            "cc": null,
            "bcc": null,
            "subject": "Foo",
            "sentAt": "2021-11-09T22:47:00Z",
            "bodyValues": {
              "1": {
                "value": "",
                "isEncodingProblem": false,
                "isTruncated": false
              }
            },
            "textBody": [
              {
                "partId": "1",
                "blobId": "Gda39a3ee5e6b4b0d3255bfef95601890afd80709",
                "size": 0,
                "name": null,
                "type": "text/plain",
                "charset": "us-ascii",
                "disposition": null,
                "cid": null,
                "language": null,
                "location": null
              }
            ],
            "htmlBody": [
              {
                "partId": "1",
                "blobId": "Gda39a3ee5e6b4b0d3255bfef95601890afd80709",
                "size": 0,
                "name": null,
                "type": "text/plain",
                "charset": "us-ascii",
                "disposition": null,
                "cid": null,
                "language": null,
                "location": null
              }
            ],
            "attachments": [],
            "calendarEvents": null
          }
        }
      },
      "1"
    ]
  ]
}
```

The curl request that triggers it (without the credentials) is:

    curl 'https://jmap.os-gravelines-1.webmsg.me/jmap/' -X POST -H 'User-Agent: Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:93.0) Gecko/20100101 Firefox/93.0' -H 'Accept: application/json;jmapVersion=rfc-8621' -H 'Accept-Language: fr-FR' --compressed -H 'Content-Type: application/json' -H 'Authorization: Basic XXXXXXXXXXXXXXXXXXXXXXXX' -H 'Origin: http://localhost:5000' -H 'DNT: 1' -H 'Connection: keep-alive' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: no-cors' -H 'Sec-Fetch-Site: cross-site' -H 'Pragma: no-cache' -H 'Cache-Control: no-cache' -H 'TE: trailers' -H 'Referer: http://localhost:5000/' --data-raw '{"using":["urn:ietf:params:jmap:core","https://cyrusimap.org/ns/jmap/quota","https://cyrusimap.org/ns/jmap/performance","https://cyrusimap.org/ns/jmap/debug","https://cyrusimap.org/ns/jmap/blob","urn:ietf:params:jmap:mail","https://cyrusimap.org/ns/jmap/search","https://cyrusimap.org/ns/jmap/mail","urn:ietf:params:jmap:submission","urn:ietf:params:jmap:vacationresponse","https://cyrusimap.org/ns/jmap/contacts","https://cyrusimap.org/ns/jmap/calendars"],"methodCalls":[["Email/set",{"accountId":"mildred@mildred.fr","create":{"draft":{"mailboxIds":{"orpjtqwuv22a7tvwdk3vl8ly":true},"removedDates":{},"addedDates":{"orpjtqwuv22a7tvwdk3vl8ly":"2021-11-09T22:47:00Z"},"keywords":{},"receivedAt":"2021-11-09T22:47:00Z","spamScore":null,"snoozed":null,"references":null,"sender":null,"replyTo":null,"messageId":["mae22z8hw8umzhd4aiab76gh@os-gravelines-1.webmsg.me"],"inReplyTo":null,"from":[{"name":null,"email":"mildred@mildred.fr"}],"to":null,"cc":null,"bcc":null,"subject":"Foo","sentAt":"2021-11-09T22:47:00Z","bodyValues":{"1":{"value":"","isEncodingProblem":false,"isTruncated":false}},"textBody":[{"partId":"1","blobId":"Gda39a3ee5e6b4b0d3255bfef95601890afd80709","size":0,"name":null,"type":"text/plain","charset":"us-ascii","disposition":null,"cid":null,"language":null,"location":null}],"htmlBody":[{"partId":"1","blobId":"Gda39a3ee5e6b4b0d3255bfef95601890afd80709","size":0,"name":null,"type":"text/plain","charset":"us-ascii","disposition":null,"cid":null,"language":null,"location":null}],"attachments":[],"calendarEvents":null}}},"1"]]}'
 
Running Cyrus version 3.2.6-2~bpo10+1 from debian buster backports packages, stack trace:

```
#0  _mime_write_xparam (buf=buf@entry=0x7ffeabc4a0d0, value=0x0, name=0x55b00d327137 "filename") at imap/jmap_mail.c:7354
#1  0x000055b00d2df1be in _emailpart_parse (bodies=0x55b0102105e0, parser=0x7ffeabc4a370, jpart=<optimized out>) at imap/jmap_mail.c:8539
#2  _emailpart_parse (jpart=<optimized out>, parser=0x7ffeabc4a370, bodies=0x55b0102105e0) at imap/jmap_mail.c:8412
#3  0x000055b00d2e046f in _email_parse_bodies (jemail=jemail@entry=0x55b01020f880, parser=parser@entry=0x7ffeabc4a370, email=email@entry=0x7ffeabc4a410)
    at imap/jmap_mail.c:8878
#4  0x000055b00d2f2288 in _parse_email (email=0x7ffeabc4a410, parser=0x7ffeabc4a370, jemail=0x55b01020f880) at imap/jmap_mail.c:9242
#5  _email_create (set_err=0x7ffeabc4a2f8, new_email=<synthetic pointer>, jemail=0x55b01020f880, req=0x7ffeabc4a730) at imap/jmap_mail.c:9630
#6  jmap_email_set (req=0x7ffeabc4a730) at imap/jmap_mail.c:11782
#7  0x000055b00d2ad903 in jmap_api (txn=txn@entry=0x7ffeabc4aac0, res=res@entry=0x7ffeabc4a9a0, settings=settings@entry=0x55b00d359b40 <my_jmap_settings>)
    at imap/jmap_api.c:833
#8  0x000055b00d2a5bba in meth_post (txn=0x7ffeabc4aac0, params=<optimized out>) at imap/http_jmap.c:376
#9  0x000055b00d2947f3 in process_request (txn=0x7ffeabc4aac0) at imap/httpd.c:1812
#10 0x000055b00d29b9b7 in http1_input (txn=<optimized out>) at imap/httpd.c:1878
#11 cmdloop (conn=0x7ffeabc4aa60) at imap/httpd.c:2028
#12 service_main (argc=<optimized out>, argv=<optimized out>, envp=<optimized out>) at imap/httpd.c:956
#13 0x000055b00d248dbc in main (argc=<optimized out>, argv=<optimized out>, envp=0x7ffeabc4fb38) at master/service.c:647
```

**Comment by elliefm** [comment]
Are you reporting that this crashes on 3.4, 3.2, or both?  The issue title says 3.4, but the description says 3.2.6.

**Comment by mildred** [comment]
Sorry, it was a little late, it is on 3.2

**Comment by mildred** [comment]
I just upgraded to 3.4 and I no longer get an error, instead I have an invalidProperties error with ` "textBody[0]/size", "textBody[0]/charset", "textBody[0]/blobId", "textBody[0]/blobId", "htmlBody[0]/size", "htmlBody[0]/charset", "htmlBody[0]/blobId", "htmlBody[0]/blobId"`

**Comment by rsto** [comment]
Cyrus does not allow to create an EmailBodyPart with both a `partId` and `blobId`.

The `partId` identifies an EmailBodyValue in the same Email containing the UTF-8 encoded body contents. If you create an email like this, then you cannot specify the `charset` and `size` properties. Instead, these properties are determined by Cyrus when it formats the JMAP Email in MIME format on disk.

**Comment by mildred** [comment]
I believe my request was incorrect, I was just trying to avoid recreating the complete mail structure and use `Email/get` results and only patch what I needed, but it might not be the correct way to do things.

In any case, it should not have made the server crash. it seems this was fixed in 3.4 anyway. Maybe it is worth looking at 3.2 to see if this makes it vulnerable somehow to bad input.
